# Site settings
title: Jason
email: jasoncluu@googlemail.com
description: > # this means to ignore newlines until "baseurl:"
  Jason Luu. Student web developer and gamer. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jasonspd.github.io" # the base hostname & protocol for your site
github_username:  jasonspd

# Build settings
markdown: kramdown